### ISSUE TITLE
stress-test can cause a class cast exception

### ISSUE THREAD

**Issue by eric** [Factual/skuld#66]
I've found this in a couple test runs:

```
java.lang.ClassCastException: java.util.HashSet cannot be cast to clojure.lang.IPersistentSet
    at clojure.core$disj.invoke(core.clj:1436) ~[clojure-1.5.1.jar:na]
    at skuld.vnode$claim_BANG_.invoke(vnode.clj:471) ~[na:na]
    at skuld.node$claim_local_BANG_$fn__4856.invoke(node.clj:290) ~[na:na]
    at skuld.node$claim_local_BANG_.invoke(node.clj:289) [na:na]
    at skuld.node$handler$handler__4893.invoke(node.clj:403) [na:na]
    at skuld.net$compile_handler$compiled_handler__4077.invoke(net.clj:297) [na:na]
    at skuld.net$handler$fn__4027$fn__4028$fn__4029.invoke(net.clj:110) [na:na]
    at skuld.net$handler$fn__4027$fn__4028.invoke(net.clj:110) [na:na]
    at clojure.core$binding_conveyor_fn$fn__4107.invoke(core.clj:1836) [clojure-1.5.1.jar:na]
    at clojure.lang.AFn.call(AFn.java:18) [clojure-1.5.1.jar:na]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
    at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
```

https://travis-ci.org/eric/skuld/jobs/28017381#L898

**Comment by eric** [comment]
~~I suspect that [this line](https://github.com/Factual/skuld/blob/eeddf7de6475b9ffc54db17f6e805cd1be1a42e2/src/skuld/vnode.clj#L313) needs to be converted to a set.~~

**Edit:** That line actually couldn't be the right place to turn it into a set.

**Comment by eric** [comment]
This has been fixed.

**Comment by aphyr** [comment]
Woo :)
