### ISSUE TITLE
Random test failure: claim-test: can't initiate claim: not a leader

### ISSUE THREAD

**Issue by eric** [Factual/skuld#73]
I'm collecting cases of random test failures to aid in tracking down issues.

https://travis-ci.org/eric/skuld/jobs/29786298#L402

```
2014-07-12T19:07:23.674 INFO  skuld.node: 127.0.0.1:13001: claim-local: claiming id from queue: #<Bytes 000001472bf8ee92800000010000000000000821>
2014-07-12T19:07:23.688 WARN  skuld.node: caught while claiming #<Bytes 000001472bf8ee92800000010000000000000821> from vnode
java.lang.IllegalStateException: can't initiate claim: not a leader.
    at skuld.vnode$claim_BANG_.invoke(vnode.clj:486) ~[na:na]
    at skuld.node$claim_local_BANG_$fn__4895.invoke(node.clj:300) ~[na:na]
    at skuld.node$claim_local_BANG_.invoke(node.clj:299) [na:na]
    at skuld.node$handler$handler__4936.invoke(node.clj:415) [na:na]
    at skuld.net$compile_handler$compiled_handler__4080.invoke(net.clj:299) [na:na]
    at skuld.net$handler$fn__4027$fn__4028$fn__4029.invoke(net.clj:110) [na:na]
    at skuld.net$handler$fn__4027$fn__4028.invoke(net.clj:110) [na:na]
    at clojure.core$binding_conveyor_fn$fn__4107.invoke(core.clj:1836) [clojure-1.5.1.jar:na]
    at clojure.lang.AFn.call(AFn.java:18) [clojure-1.5.1.jar:na]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
    at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
```

**Comment by eric** [comment]
Added more logging to try to track it down in cbb89ef475064b87928869bb104aaa7575fc643b.

**Comment by eric** [comment]
The vnode throws an exception if a task tries to be claimed in [`claim!`](https://github.com/Factual/skuld/blob/8f00a3fce036479c3342fab28105c1f97de61798/src/skuld/vnode.clj#L477-L478) if the vnode is not the leader.

There does not appear to be any logic in the node in [`claim!`](https://github.com/Factual/skuld/blob/8f00a3fce036479c3342fab28105c1f97de61798/src/skuld/node.clj#L302-L304) or [`claim-local!`](https://github.com/Factual/skuld/blob/8f00a3fce036479c3342fab28105c1f97de61798/src/skuld/node.clj#L282-L293) that defends against trying to claim from a vnode who isn't the leader.

I'm having trouble reasoning out what the logic should be here, so any input from @aphyr would be appreciated.

**Comment by ztellman** [comment]
Just to chime in on @aphyr's behalf, he's currently traveling and will be back around the end of next week.

**Comment by eric** [comment]
@ztellman: Yeah, I understand.

**Comment by eric** [comment]
Found another instance of this failure: https://travis-ci.org/eric/skuld/jobs/29844927#L437

**Comment by eric** [comment]
I believe I figured out what the issue is:

The queue for a node is supposed to only contain IDs for tasks where the local node is the leader of the vnode [as described here](https://github.com/Factual/skuld/blob/8f00a3fce036479c3342fab28105c1f97de61798/src/skuld/queue.clj#L9-L11):

```
  There's one queue per node. That queue is a rough approximation of all tasks
  which could be claimed on the local node--e.g. it contains only tasks for
  which the local node has a leader vnode.
```

The problem is if a vnode has recently been demoted, the node queue will still have a number of tasks that it no longer owns, so they need to be ignored.

**Comment by aphyr** [comment]
Bingo, good catch @eric. I was gonna say that the queue should exclude those items, but there's still a race there if the vnode shuts down just after handing you a record. Retry logic has to be embedded further upstream.
